# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Admin:
            algorithm: auto

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/admin/login
            stateless: true
            json_login:
                check_path: /admin/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/admin
            stateless: true
            jwt: ~

        api_protected:
            pattern: ^/(church|member|member-transfer)
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/church, roles: ROLE_ADMIN }
        - { path: ^/member, roles: ROLE_ADMIN }
        - { path: ^/member-transfer, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER